도메인 모델 리팩토링 및 쿠폰 발급 유효성 검사 로직 추가
dev-couponify/coupon pull request #12
Opened 2024-12-10 08:29 UTC by eggnee

## ✅ What is this PR

- 쿠폰 도메인 모델과 IssuedCoupon 도메인 모델을 리팩토링하여 JPA 의존 객체와 도메인 객체 간의 변환 작업을 최소화하여 코드 복잡도를 줄였습니다. 
- 쿠폰 발급 시 잔여 수량을 체크하는 로직을 추가했습니다.
- 쿠폰 잔여 수량이 0이 되면 자동으로 쿠폰 상태를 SOLD_OUT으로 변경하는 로직을 구현하였습니다.

## 📄 Changes Made

- Coupon 도메인 모델 리팩토링
- IssuedCoupon 도메인 모델 리팩토링
- 쿠폰 발급 유효성 검사에 잔여 수량 체크 추가
- 쿠폰 발급 시 잔여 수량이 0일 경우 쿠폰 상태를 SOLD_OUT 으로 자동 변경
- 확장성을 고려하여 쿠폰 상태 enum 값 추가 및 변경

## 🙋🏻‍ Review Point

> `Coupon` `Quantity` 도메인 내 비즈니스 로직 메서드를 세분화하여 구현한 부분에 대해, 메서드가 너무 세분화된 것 아닌지 궁금합니다.

## Issue
- close #11

2024-12-10 12:21 UTC, choi-ys commented on service/coupon-api/src/main/java/com/couponify/couponapi/application/CouponService.java
>      final IssuedCoupon savedIssuedCoupon = issuedCouponRepository.save(issuedCoupon);
Coupon Domain이 JPA Entity의 역할도 같이 수행하므로, 명시적으로 JpaRepository의 save메서드를 호출하지 않고 트랜잭션 범위 안에서 변경 감지를 통해 잔여 수량을 감소할 수 있을 것 같아요

2024-12-10 12:23 UTC, choi-ys commented on service/coupon-api/src/main/java/com/couponify/couponapi/application/CouponService.java
> +    final IssuedCoupon issuedCoupon = IssuedCoupon.of(userId, coupon);
Coupon 도메인이 JpaEntity로 정의 되어, IssuedCouponRepository의 save를 명시적으로 호출하여 쿠폰 수량을 감소하기보다, 트랜잭션 커밋 시점에 변경 감지를 통해 업데이트 하도록 구성해보는건 어떠세요?

2024-12-10 12:50 UTC, choi-ys commented
외부 의존성을 분리하기 위해 여러 방법을 시도하시는 과정에서 고민이 많으셨을 것 같아요.
참고하면 좋을 만한 내용을 남겼으니 고민해보시면 좋을 것 같아요.

고생 많으셨습니다 👍👍

2024-12-10 13:06 UTC, choi-ys requested changes

2024-12-10 13:06 UTC, re-mora commented on service/coupon-api/src/main/java/com/couponify/couponapi/presentation/request/CouponCreateRequest.java
> +  @NotNull(message = "발급 시작 일시는 필수입니다.")
`발급 시작 일시는 현재 시간보다 이전일 수 없다`를 위한 값 검증도 같이 표현되면 좋을 것 같아요

2024-12-10 13:06 UTC, re-mora commented on service/coupon-domain/src/main/java/com/couponify/coupondomain/domain/coupon/Coupon.java
> +    if (this.quantity.isNoQuantity()) {
수량이 없다라는 의미의 `hasNoQuantity` 혹은 수량이 0임을 의미하는 `isZero`는 어떠세요?

2024-12-10 13:06 UTC, re-mora commented on service/coupon-domain/src/main/java/com/couponify/coupondomain/domain/coupon/Coupon.java
> +      throw new IllegalArgumentException("쿠폰 발급 기간이 아닙니다.");
RuntimeException 기반의 BusinessException이 정의 되어있으니, 상위 타입 기반의 상세 Exception 클래스를 정의해서 보다 상세하게 처리하면 어떨까요?

2024-12-10 13:06 UTC, re-mora commented on service/coupon-domain/src/main/java/com/couponify/coupondomain/domain/coupon/Coupon.java
> +    if (!this.issueStartAt.isBefore(LocalDateTime.now()) || !this.issueEndAt.isAfter(
두개 이상의 조건을 만족해야 하는 해당 분기문이 어떤 경우를 검증하는지 바로 이해하기 조금 어려울 수 도 있을 것 같아요.

해당 분기문을 별도 메서드로 추출해서 발급 가능 기간이 아니라는 의미의 `isNotIssuePeriod` 와 같은 메서드로 표현해보면 어떨까요?

2024-12-10 13:06 UTC, re-mora commented on service/coupon-domain/src/main/java/com/couponify/coupondomain/domain/coupon/CouponStatus.java
> +  AVAILABLE("발급 가능"), SOLD_OUT("수량 소진"), EXPIRED("발급 만료");
EXPIRED를 발급 만료로 설명하고 있어서, 수량이 소진되어 발급이 불가능할 수 도 있다고 생각할 수 있을것 같아요. 조금 더 명확하게 `기간 만료`로 표현해보는건 어떠세요?

2024-12-10 13:06 UTC, re-mora commented on service/coupon-domain/src/main/java/com/couponify/coupondomain/domain/coupon/CouponStatus.java
> +    return this.equals(AVAILABLE);
Enum 객체의 각 상수는 public static final 필드 이면서 Enum 객체는 Class Loader에 의해 메서드 영역에 할당되므로 프로그램 종료 전까지 동일 객체에 접근 해요.

따라서 주소값을 비교하는  '=='을 통해서도 동일 객체 여부를 비교할 수 있어요. 

소나큐브 같은 품질 검사 툴에서 보통은 '==' 사용을 룰로 정하고 있지만, enum의 equals 내부 구현을 보시면 이미 '=='으로 비교하고 있기 때문에 '=='과 'equals'의 차이점만 알고 계시다면 Enum의 객체 동일성 비교 시 어떤 방법을 적용 하셔도 상관 없을 것 같아요.

2024-12-10 13:06 UTC, re-mora commented on service/coupon-domain/src/main/java/com/couponify/coupondomain/domain/coupon/Quantity.java
> +  public boolean isSufficientFor(int quantityToCompare) {
해당 메서드의 이름만 보고 어떤 역할을 하는 메서드인지 바로 파악하기 조금 어려운 것 같아요.
해당 메서드가 언제 호출 되고 어떤 역할을 수행하는 걸까요?

2024-12-10 13:06 UTC, re-mora commented on service/coupon-domain/src/main/java/com/couponify/coupondomain/domain/issuedCoupon/IssuedCoupon.java
> +  @JoinColumn(name = "coupon_id")
```java
  @JoinColumn(
          name = "coupon_id",
          foreignKey = "FK_외래키_제약조건_이름",
          nullable = false
  )
```
조금 더 명시적인 설정들을 추가해 보면 어떨까요?

2024-12-10 13:06 UTC, re-mora commented on service/coupon-api/src/main/java/com/couponify/couponapi/application/CouponService.java
> +    final Coupon coupon = CouponCreateRequest.toDomain(couponCreateRequest);
👍👍

2024-12-10 13:06 UTC, re-mora commented on service/coupon-api/build.gradle
> +    implementation("org.springframework:spring-tx")
👍👍

2024-12-11 04:59 UTC, eggnee commented on service/coupon-domain/src/main/java/com/couponify/coupondomain/domain/coupon/Coupon.java
> +      throw new IllegalArgumentException("쿠폰 발급 기간이 아닙니다.");
지금 예외 처리 관련 클래스가 api 모듈에 있어서 일단은 이렇게 했습니다 !

2024-12-11 05:04 UTC, eggnee commented on service/coupon-domain/src/main/java/com/couponify/coupondomain/domain/coupon/Quantity.java
> +  public boolean isSufficientFor(int quantityToCompare) {
쿠폰 발급 시에 발급할 수량만큼의 잔여 수량이 존재하는지 확인합니다!

2024-12-11 05:07 UTC, eggnee commented on service/coupon-api/src/main/java/com/couponify/couponapi/application/CouponService.java
> +    final IssuedCoupon issuedCoupon = IssuedCoupon.of(userId, coupon);
좋은 것 같습니다!

2024-12-11 05:30 UTC, eggnee commented on service/coupon-api/src/main/java/com/couponify/couponapi/presentation/request/CouponCreateRequest.java
> +  @NotNull(message = "발급 시작 일시는 필수입니다.")
이에 대해 고민해봤는데 전산 상의 오류로 이미 발급 시작한 쿠폰을 등록할 일도 있을 수 있지 않을까? 라는 생각이 들어서 제외했어요
어떻게 생각하세요??

2024-12-11 05:30 UTC, eggnee commented on service/coupon-domain/src/main/java/com/couponify/coupondomain/domain/coupon/Coupon.java
> +    if (!this.issueStartAt.isBefore(LocalDateTime.now()) || !this.issueEndAt.isAfter(
넵 알겠습니다!

2024-12-11 08:54 UTC, re-mora commented on service/coupon-api/src/main/java/com/couponify/couponapi/application/CouponSchedulerService.java
> +public class CouponSchedulerService {
해당 스케줄러는 어디에서 사용하게 되는 걸까요?

2024-12-11 08:55 UTC, eggnee commented on service/coupon-api/src/main/java/com/couponify/couponapi/application/CouponSchedulerService.java
> +public class CouponSchedulerService {
매일 자정에 기한이 만료된 쿠폰을 기한 만료 상태로 변경합니다!

2024-12-11 08:59 UTC, choi-ys commented
안녕하세요 아린님
전반적으로 잘 수정하신 것 같아요
다만 스케쥴러를 추가하셨는데 어떤 의도로 추가하셨는지 알 수 있을까요?

2024-12-11 08:59 UTC, choi-ys requested changes
안녕하세요 아린님 전반적으로 잘 수정하신 것 같아요 다만 스케쥴러를 추가하셨는데 어떤 의도로 추가하셨는지 알 수 있을까요?

2024-12-11 08:59 UTC, choi-ys commented on service/coupon-domain/src/main/java/com/couponify/coupondomain/domain/issuedCoupon/IssuedCoupon.java
> +  private Coupon coupon;
👍

2024-12-11 09:00 UTC, eggnee commented
> 안녕하세요 아린님 전반적으로 잘 수정하신 것 같아요 다만 스케쥴러를 추가하셨는데 어떤 의도로 추가하셨는지 알 수 있을까요?

매일 자정에 기한이 만료된 쿠폰을 기한 만료 상태로 변경합니다!

2024-12-11 09:05 UTC, choi-ys approved these changes
넵 이해 했습니다! 
추가적으로 더 수정이 필요하거나 궁금한 부분은 없어서
PR 종료 하도록 하겠습니다.

고생 많으셨어요!

2024-12-11 09:05 UTC, merged