공통 응답, 커스텀 예외 처리 객체 생성
dev-couponify/coupon pull request #6
Opened 2024-12-04 08:10 UTC by eggnee

## ✅ What is this PR

- 공통 응답 객체와 커스텀 예외 처리 객체를 생성하여 일관된 API 응답 형식을 유지하고, 예외 발생 시 일관된 방식으로 처리할 수 있도록 합니다.

## 📄 Changes Made

- 커스텀 예외 처리 객체 생성
- 공통 응답 객체 생성
- ResponseBodyAdvice를 활용한 공통 응답 상태 코드 설정

## Test

- [x] http 테스트 작성

![image](https://github.com/user-attachments/assets/3d18861d-3f09-472e-bf27-0e3ca102fa17)

## 🙋🏻‍ Review Point

> ApiResponse를 직접 반환할 때 HTTP 상태 코드가 항상 200으로 설정되는 문제가 발생했습니다. 
> 이를 해결하기 위해 ResponseBodyAdvice를 사용하여 HTTP 상태 코드가 자동으로 설정되도록 구현하였습니다.
> `ResponseBodyAdvice`는 Spring에서 응답 본문을 반환하기 전에 응답 데이터를 가로채서 후처리할 수 있게 해주는 인터페이스로, 
> 이를 통해 응답 본문에 맞는 HTTP 상태 코드를 자동으로 설정할 수 있습니다.

## Reference
- [공통 응답용 ApiResponse 만들기](https://velog.io/@tkdwns414/Spring-Boot-%EA%B3%B5%ED%86%B5-%EC%9D%91%EB%8B%B5%EC%9A%A9-ApiResponse-%EB%A7%8C%EB%93%A4%EA%B8%B0)

## Issue
- close #5

2024-12-05 13:07 UTC, re-mora commented on service/coupon-api/src/main/java/com/sparta/order/couponapi/common/exception/BusinessException.java
일관된 예외 반환을 위한 상위 타입의 Exception 설계 👍

2024-12-05 13:12 UTC, choi-ys commented on service/coupon-api/src/main/java/com/sparta/order/couponapi/common/exception/BusinessExceptionHandler.java
현재 구현된 ExceptionHandler에서는 BusinessException 타입이 아닌 경우는 `INTERNAL_SERVER_ERROR`를 반환하도록 구현 되어 있어요.
서버 에러가 아닌 경우에도 `INTERNAL_SERVER_ERROR`가 반환되는 문제점이 발생할 수 있을 것 같아요
이를 위해 Spring에서는 `DefaultHandlerExceptionResolver`에서 기본 적인 예외를 반환하고 있어요.
DefaultHandlerExceptionResolver 클래스를 직접 확인해보시면 아래와 같이 다루고 있는 예외 목록을 확인해 볼 수 있어요
![image](https://github.com/user-attachments/assets/e7ebeb28-02c7-4004-83a3-d74b088d2d19)

DefaultHandlerExceptionResolver에 대한 자세한 내용을 참고 할 수 있는 링크를 첨부드리니 한번 읽어보셔도 좋을 것 같아요.
[SpringDocs-DefaultHandlerExceptionResolver](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/mvc/support/DefaultHandlerExceptionResolver.html)

2024-12-05 13:26 UTC, choi-ys requested changes
안녕하세요 아린님
일관된 예외 처리를 위해 상위 타입의 Exception을 정의하고, 상위 타입의 Exception을 기반으로 상세한 오류 처리를 위해 예외와 에러 코드를 정의하신 부분이 좋았습니다.

다만 구성하신 Exception Handler와 일관된 API 응답을 위해 정의한 ApiResponse 객체 관련해서 고민해 볼만한 내용을 리뷰로 남겨 드렸으니 읽어보시고 한번 고민해 보시면 좋을 것 같아요!

고생 많으셨습니다 👍

2024-12-05 13:26 UTC, choi-ys commented on service/coupon-api/src/main/java/com/sparta/order/couponapi/common/exception/CouponErrorCode.java
상세한 예외 처리를 위해 일관된 상위 Exception 기반의 예외와 에러코드 정의 👍 👍

2024-12-05 13:26 UTC, choi-ys commented on service/coupon-api/src/main/java/com/sparta/order/couponapi/common/exception/CouponErrorCode.java
상세한 예외 처리를 위해 일관된 상위 Exception 기반의 예외와 에러코드 정의 👍 👍

2024-12-05 13:26 UTC, choi-ys commented on service/coupon-api/src/main/java/com/sparta/order/couponapi/common/exception/CouponException.java
👍 👍

2024-12-05 13:26 UTC, choi-ys commented on service/coupon-api/src/main/java/com/sparta/order/couponapi/common/response/ApiResponse.java
일관된 응답 반환을 위해 포장 객체를 정의하신것 같아요.

- ApiResponse 객체에 응답 시간 등의 필드가 추가되어야 하는 경우
- Response Header에 문서 링크, 생성된 리소스를 조회할 수 있는 경로 등이 추가적으로 설정되어야 하는 경우

ApiResponse 기반의 API 제공하는 시스템에서 위와 같은 추가적인 요구사항이 발생한다면 어떨까요?
ApiResponse 객체의 필드값 변경에 따라 Client는 응답 수신 로직을 수정 해야하고, 응답 객체 수정으로 인해 API에 오류가 발생하는 현상을 방지하기 위해 /api/v1, /api/v2와 같이 버저닝을 고려해야 할 것 같아요.

이미 spring-web에서 제공하는 ResponseEntity를 통해서 위와 같은 요구사항을 달성하는 건 충분히 가능할 것 같아요.
일관된 응답을 위해 포장 객체를 사용하는 것이 또 다른 관리 포인트를 만들게 되는 건 아닌지 고민해 보시면 좋을 것 같아요.

2024-12-06 15:31 UTC, eggnee commented
> 안녕하세요 아린님 일관된 예외 처리를 위해 상위 타입의 Exception을 정의하고, 상위 타입의 Exception을 기반으로 상세한 오류 처리를 위해 예외와 에러 코드를 정의하신 부분이 좋았습니다.
> 
> 다만 구성하신 Exception Handler와 일관된 API 응답을 위해 정의한 ApiResponse 객체 관련해서 고민해 볼만한 내용을 리뷰로 남겨 드렸으니 읽어보시고 한번 고민해 보시면 좋을 것 같아요!
> 
> 고생 많으셨습니다 👍

넵 감사합니다 !

2024-12-07 05:03 UTC, eggnee commented
> 공통 응답 객체 제거 및 전역 예외 처리 구현
> - ApiResponse와 같은 공통 응답 객체 제거 (중복성 문제 해결)
> - 전역 예외 처리 시 ResponseEntity의 body에 ErrorResponse 반환

수정 완료하여 푸시했습니다

2024-12-09 10:52 UTC, merged